name: Processo di Build

on: ["push", "pull_request"]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Enviroment-assignment

    steps:
      - uses: actions/checkout@v3
      - name: Inizializzazione JDK 1.8
        uses: actions/setup-java@v3
        with:
          java-version: '8.0.332+9'
          distribution: 'temurin'
          cache: 'maven'
      - name: Utilizzo della cache di Maven
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
            
      - name: Test e build
        run: mvn  -B install --file pom.xml
      - name: Aggiornamento badge Coveralls 
        run: mvn -DrepoToken=${{ secrets.COVERALL_TOKEN }}  jacoco:report coveralls:report
